SurfnPaddleRails/config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'show/:id' => 'home#show', :as => :id

end

SurfnPaddleRails/app/models/post.rb
class Post
  attr_accessor :id, :title, :body, :summary, :author, :created_at

  def initialize(hash)
    @id         = hash[:id]
    @title      = hash[:title]
    @body       = hash[:body]
    @summary    = hash[:summary]
    @author     = hash[:author]
    @created_at = hash[:created_at] || Time.now
  end

  def self.all
    unless defined?(@@posts)
      @@posts = [
          Post.new(
            :id         => 1,
            :title      => "Vogel",
            :body       => "Well, the way they make shows is, they make one show. That show's called a pilot. Then they show that show to the people who make shows, and on the strength of that one show they decide if they're going to make more shows. Some pilots get picked and become television programs. Some don't, become nothing. She starred in one of the ones that became nothing.
                          Proin ut quam eros. Donec sed lobortis diam. Nulla nec odio lacus. Quisque porttitor egestas dolor in placerat. Nunc vehicula dapibus ipsum. Duis venenatis risus non nunc fermentum dapibus. Morbi lorem ante, malesuada in mollis nec, auctor nec massa. Aenean tempus dui eget felis blandit at fringilla urna ultrices. Suspendisse feugiat, ante et viverra lacinia, lectus sem lobortis dui, ultricies consectetur leo mauris at tortor. Nunc et tortor sit amet orci consequat semper. Nulla non fringilla diam.",
            :summary    => "Some Ipsum",
            :author     => "Jim Rome",
            :created_at => (1..10).to_a.sample.months.ago
          ),
          Post.new(
            :id         => 2,
            :title      => "George",
            :body       => "Nullam eros mi, mollis in sollicitudin non, tincidunt sed enim. Sed et felis metus, rhoncus ornare nibh. Ut at magna leo. Suspendisse egestas est ac dolor imperdiet pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porttitor, erat sit amet venenatis luctus, augue libero ultrices quam, ut congue nisi risus eu purus. Cras semper consectetur elementum. Nulla vel aliquet libero. Vestibulum eget felis nec purus commodo convallis. Aliquam erat volutpat.
                            Proin ornare ligula eu tellus tempus elementum. Aenean bibendum iaculis mi, nec blandit lacus interdum vitae. Vestibulum non nibh risus, a scelerisque purus. Ut vel arcu ac tortor adipiscing hendrerit vel sed massa. Fusce sem libero, lacinia vulputate interdum non, porttitor non quam. Aliquam sed felis ligula. Duis non nulla magna.",
            :summary    => "Some More Ipsum",
            :author     => "Tony Kornheiser",
            :created_at => (1..10).to_a.sample.months.ago
          ),
          Post.new(
            :id         => 3,
            :title      => "Ellis",
            :body       => "Integer elementum massa at nulla placerat varius. Suspendisse in libero risus, in interdum massa. Vestibulum ac leo vitae metus faucibus gravida ac in neque. Nullam est eros, suscipit sed dictum quis, accumsan a ligula. In sit amet justo lectus. Etiam feugiat dolor ac elit suscipit in elementum orci fringilla. Aliquam in felis eros. Praesent hendrerit lectus sit amet turpis tempus hendrerit. Donec laoreet volutpat molestie. Praesent tempus dictum nibh ac ullamcorper. Sed eu consequat nisi. Quisque ligula metus, tristique eget euismod at, ullamcorper et nibh. Duis ultricies quam egestas nibh mollis in ultrices turpis pharetra. Vivamus et volutpat mi. Donec nec est eget dolor laoreet iaculis a sit amet diam.
                            Proin ornare ligula eu tellus tempus elementum. Aenean bibendum iaculis mi, nec blandit lacus interdum vitae. Vestibulum non nibh risus, a scelerisque purus. Ut vel arcu ac tortor adipiscing hendrerit vel sed massa. Fusce sem libero, lacinia vulputate interdum non, porttitor non quam. Aliquam sed felis ligula. Duis non nulla magna. ",
            :summary    => "Crazy Ipsum",
            :author     => "Mike Wilbon",
            :created_at => (1..10).to_a.sample.months.ago
          ),
          Post.new(
            :id         => 4,
            :title      => "Hill",
            :body       => "Maecenas eu placerat ante. Fusce ut neque justo, et aliquet enim. In hac habitasse platea dictumst. Nullam commodo neque erat, vitae facilisis erat. Cras at mauris ut tortor vestibulum fringilla vel sed metus. Donec interdum purus a justo feugiat rutrum. Sed ac neque ut neque dictum accumsan. Cras lacinia rutrum risus, id viverra metus dictum sit amet. Fusce venenatis, urna eget cursus placerat, dui nisl fringilla purus, nec tincidunt sapien justo ut nisl. Curabitur lobortis semper neque et varius. Etiam eget lectus risus, a varius orci. Nam placerat mauris at dolor imperdiet at aliquet lectus ultricies. Duis tincidunt mi at quam condimentum lobortis.
                            Proin suscipit luctus orci placerat fringilla. Donec hendrerit laoreet risus eget adipiscing. Suspendisse in urna ligula, a volutpat mauris. Sed enim mi, bibendum eu pulvinar vel, sodales vitae dui. Pellentesque sed sapien lorem, at lacinia urna. In hac habitasse platea dictumst. Vivamus vel justo in leo laoreet ullamcorper non vitae lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin bibendum ullamcorper rutrum.",
            :summary    => "What More Ipsum",
            :author     => "Spike Lee",
            :created_at => (1..10).to_a.sample.months.ago
          ),
          Post.new(
            :id         => 5,
            :title      => "Stuckey",
            :body       => "Nullam eros mi, mollis in sollicitudin non, tincidunt sed enim. Sed et felis metus, rhoncus ornare nibh. Ut at magna leo. Suspendisse egestas est ac dolor imperdiet pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porttitor, erat sit amet venenatis luctus, augue libero ultrices quam, ut congue nisi risus eu purus. Cras semper consectetur elementum. Nulla vel aliquet libero. Vestibulum eget felis nec purus commodo convallis. Aliquam erat volutpat.
                            Etiam aliquam sem ac velit feugiat elementum. Nunc eu elit velit, nec vestibulum nibh. Curabitur ultrices, diam non ullamcorper blandit, nunc lacus ornare nisi, egestas rutrum magna est id nunc. Pellentesque imperdiet malesuada quam, et rhoncus eros auctor eu. Nullam vehicula metus ac lacus rutrum nec fermentum urna congue. Vestibulum et risus at mi ultricies sagittis quis nec ligula. Suspendisse dignissim dignissim luctus. Duis ac dictum nibh. Etiam id massa magna. Morbi molestie posuere posuere.",
            :summary    => "Even More Ipsum",
            :author     => "Reggie Miller",
            :created_at => (1..10).to_a.sample.months.ago
          )
      ]
    end
    @@posts
  end

  def self.find(id)
    all.select{|post| post.id == id}.first
  end

end

SurfnPaddleRails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

SurfnPaddleRails/app/controllers/ellis_controller.rb
class EllisController < ApplicationController
end

SurfnPaddleRails/app/controllers/george_controller.rb
class GeorgeController < ApplicationController
end

SurfnPaddleRails/app/controllers/hill_controller.rb
class HillController < ApplicationController
end

SurfnPaddleRails/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @posts = Post.all
    @ordered_posts = @posts.sort_by {|post| post.created_at}.reverse
    @post = @ordered_posts.first
  end

  def show
    @post = Post.find(params[:id].to_i)
  end

end

SurfnPaddleRails/app/controllers/stuckey_controller.rb
class StuckeyController < ApplicationController
end

SurfnPaddleRails/app/helpers/application_helper.rb
module ApplicationHelper
end

SurfnPaddleRails/app/helpers/ellis_helper.rb
module EllisHelper
end

SurfnPaddleRails/app/helpers/george_helper.rb
module GeorgeHelper
end

SurfnPaddleRails/app/helpers/hill_helper.rb
module HillHelper
end

SurfnPaddleRails/app/helpers/home_helper.rb
module HomeHelper
end

SurfnPaddleRails/app/helpers/stuckey_helper.rb
module StuckeyHelper
end

SurfnPaddleRails/app/views/home/index.html.erb
<p><h1><%=@post.title%></h1></p>

<p><h2><%=@post.body%></h2></p>

<p><h5><%=@post.summary%></h5></p>

<p><h5><%=@post.author%></h5></p>

<p><h6><%=@post.created_at.strftime('%B %d, %Y') %></h6></p>

SurfnPaddleRails/app/views/home/show.html.erb
<p><h1><%=@post.title%></h1></p>

<p><h2><%=@post.body%></h2></p>

<p><h5><%=@post.summary%></h5></p>

<p><h5><%=@post.author%></h5></p>

<p><h6><%=@post.created_at.strftime('%B %d, %Y') %></h6></p>

SurfnPaddleRails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Week 4 Lab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Bootstrap Core CSS -->
  <link href="css/bootstrap.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="clean-blog.scss" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
      <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header page-scroll">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="index.html">Go Pacers Blog</a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                  <li class = "gold">
                      <a href="index.html">Home</a>
                  </li>
                  <li>
                      <a href="about.html">About</a>
                  </li>
                  <li>
                      <a href="contact.html">Contact</a>
                  </li>
              </ul>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
  </nav>

  <!-- Page Header -->
  <!-- Set your background image for this header on the line below. -->
  <header class="intro-header" style="background-image: url('/assets/pacers.jpg')">
      <div class="container">
          <div class="row">
              <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                  <div class="site-heading">
                      <span class="subheading">An Iron Yard Production Est. Summer 2015</span>
                  </div>
              </div>
          </div>
      </div>
  </header>
  <!-- Main Content -->
  <div class="container">
      <div class="row">
          <div class="col-md-6">
            <p>  <%=yield%> </p>
          </div>
          <div class="col-md-6">
            <div class = "author">

              <div class = "poster_pic">
                <%= image_tag("img.jpeg") %>
              </div>

              <div class = "poster">
              <p> Posted by: <%=@post.author%> </p>
              </div>

              <p class = "social_media"> Twitter | Facebook | Instagram </p>

              <div class = "advert">
                <%= image_tag("pacers_logo.gif") %>
              </div>

              <div class = "ad_write-up">
              <p> Out believe has request not how comfort evident. Up delight cousins we feeling minutes. Genius has looked end piqued spring. Down has rose feel find man. Learning day desirous informed expenses material returned six the. She enabled invited exposed him another. Reasonably conviction solicitude me mr at discretion reasonable. Age out full gate bed day lose. </p>
              </div>
            </div>
          </div>
      </div>
  </div>
  <footer>
      <div class="container">
          <div class="row">
              <div class="col-sm-12">
                <div class = "picture_container">
                  <p class = "fav">  Favorite Players </p>
                  <div class="george">
                    <%=link_to image_tag("Paul-George-Jump.jpg"), id_path(:id => 1) %>
                    <p> George </p>
                  </div>
                  <div class="hill">
                    <%=link_to image_tag("George_Hill_Pacers.jpg"), id_path(:id => 2) %>
                    <p> Hill </p>
                  </div>
                  <div class="ellis">
                    <%=link_to image_tag("Monta_Ellis.jpg"), id_path(:id => 3) %>
                    <p> Ellis </p>
                </div>
                <div class="stuckey">
                  <%=link_to image_tag("stucky.jpg"), id_path(:id => 4) %>
                  <p> Stuckey </p>
                </div>
              </div>
              <div class = "btm_pic">
                <p class = "p_blog"> Pacers Blog </p>
                <p class = "players"> George | Hill | Ellis | Stuckey </p>
              </div>
      </div>
    </div>
  </div>
  </footer>
</body>
</html>